/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.oscarmaestre.chip8;

import java.awt.Graphics;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author usuario
 */
public class Interfaz extends javax.swing.JFrame {

    private final int MODO_DETENIDO     = 0;
    private final int MODO_PASO_A_PASO  = 1;
    
    int modoEjecucion=MODO_DETENIDO;
    CPU cpu;
    PantallaJPanel pantallaCPU;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        pantallaCPU=new PantallaJPanel();
        Teclado teclado=new Teclado();
        teclado.setValorTecla((byte)13);
        pantallaCPU.setPanel(pantalla);
        System.out.println("Listo");
        cpu=new CPU(pantallaCPU, teclado);
        cpu.dibujarAlgo();
        System.out.println("Ok");
    }

    @Override
    public void paint(Graphics g) {
        
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        pantallaCPU.actualizar();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantalla = new javax.swing.JPanel();
        btnPaso = new javax.swing.JButton();
        btnEjecutar = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuLoad = new javax.swing.JMenuItem();
        jmenuTest = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPaso.setText("Paso a paso");
        btnPaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasoActionPerformed(evt);
            }
        });

        btnEjecutar.setText("Sin parar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        btnNext.setText("Siguiente instruccion");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pantallaLayout = new javax.swing.GroupLayout(pantalla);
        pantalla.setLayout(pantallaLayout);
        pantallaLayout.setHorizontalGroup(
            pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(btnPaso)
                .addGap(18, 18, 18)
                .addComponent(btnEjecutar)
                .addGap(41, 41, 41)
                .addComponent(btnNext)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        pantallaLayout.setVerticalGroup(
            pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPaso)
                    .addComponent(btnEjecutar)
                    .addComponent(btnNext))
                .addContainerGap(437, Short.MAX_VALUE))
        );

        getContentPane().add(pantalla, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jMenuLoad.setText("Load");
        jMenuLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLoadActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuLoad);

        jmenuTest.setText("Test");
        jmenuTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuTestActionPerformed(evt);
            }
        });
        jMenu1.add(jmenuTest);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLoadActionPerformed
        JFileChooser dlgAbrirFichero=new JFileChooser();
        int codigoExito;
        codigoExito = dlgAbrirFichero.showOpenDialog(this);
        if (codigoExito == JFileChooser.APPROVE_OPTION){
            String path=dlgAbrirFichero.getSelectedFile().getAbsolutePath();
            byte[] encoded;
            try {
                //encoded = Files.readAllBytes(Paths.get(path));
                cpu.cargarArchivo(path);
            } catch (IOException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }
    }//GEN-LAST:event_jMenuLoadActionPerformed

    private void btnPasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasoActionPerformed
        cpu.ejecutarInstruccion();
    }//GEN-LAST:event_btnPasoActionPerformed

    private void jmenuTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuTestActionPerformed
        String rutaJuegoPrueba="/home/usuario/Descargas/Roger.ch8";
        try {
            cpu.cargarArchivo(rutaJuegoPrueba);
            System.out.println("Cargado el archivo");
            System.out.println(this.cpu.memoria.getVolcado(0x200, 0xfff));
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmenuTestActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        cpu.ejecutar(0x200);
    }//GEN-LAST:event_btnEjecutarActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        cpu.ejecutarInstruccion();
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPaso;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuLoad;
    private javax.swing.JMenuItem jmenuTest;
    private javax.swing.JPanel pantalla;
    // End of variables declaration//GEN-END:variables
}
